/* Generated By:JavaCC: Do not edit this line. TyRuBaParserConstants.java */
package tyRuBa.parser;

public interface TyRuBaParserConstants {

  int EOF = 0;
  int WHITECHAR = 1;
  int COMMENT = 2;
  int SINGLE_LINE_COMMENT = 3;
  int FORMAL_COMMENT = 4;
  int MULTI_LINE_COMMENT = 5;
  int INTEGER_LITERAL = 6;
  int DECIMAL_LITERAL = 7;
  int HEX_LITERAL = 8;
  int OCTAL_LITERAL = 9;
  int FLOATING_POINT_LITERAL = 10;
  int EXPONENT = 11;
  int STRING_LITERAL = 12;
  int INCLUDE = 13;
  int LIBRARY = 14;
  int GENERATE = 15;
  int NOT = 16;
  int EXISTS = 17;
  int NODUP = 18;
  int FINDALL = 19;
  int COUNTALL = 20;
  int UNIQUE = 21;
  int TEST = 22;
  int MODES = 23;
  int IS = 24;
  int REALLY = 25;
  int TYPEDEF = 26;
  int REPRESENTED_AS = 27;
  int MODEEND = 28;
  int DET = 29;
  int SEMIDET = 30;
  int MULTI = 31;
  int NONDET = 32;
  int BOUND = 33;
  int DEF = 34;
  int FACT = 35;
  int OF = 36;
  int PERSISTENT = 37;
  int OR = 38;
  int AND = 39;
  int TYPE = 40;
  int LPAREN = 41;
  int RPAREN = 42;
  int LBRACKET = 43;
  int RBRACKET = 44;
  int LANGLE = 45;
  int RANGLE = 46;
  int SEMICOLON = 47;
  int COMMA = 48;
  int DOT = 49;
  int HASH = 50;
  int UNQUOTE = 51;
  int VERTSLASH = 52;
  int SLASH = 53;
  int WHEN = 54;
  int PLUS = 55;
  int STAR = 56;
  int STRICT = 57;
  int SPECIAL = 58;
  int SPECIAL_CHAR = 59;
  int IDENTIFIER = 60;
  int VARIABLE = 61;
  int TEMPLATE_VAR = 62;
  int JAVA_CLASS = 63;
  int REGEXP = 64;
  int LOWCASE = 65;
  int UPCASE = 66;
  int LETTER = 67;
  int DIGIT = 68;
  int QUOTEDCODE = 73;

  int DEFAULT = 0;
  int inBraces = 1;
  int inNestedBraces = 2;

  String[] tokenImage = {
    "<EOF>",
    "<WHITECHAR>",
    "<COMMENT>",
    "<SINGLE_LINE_COMMENT>",
    "<FORMAL_COMMENT>",
    "<MULTI_LINE_COMMENT>",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<EXPONENT>",
    "<STRING_LITERAL>",
    "\"#include\"",
    "\"#library\"",
    "\"#generate\"",
    "\"NOT\"",
    "\"EXISTS\"",
    "\"NODUP\"",
    "\"FINDALL\"",
    "\"COUNTALL\"",
    "\"UNIQUE\"",
    "\"TEST\"",
    "\"MODES\"",
    "\"IS\"",
    "\"REALLY\"",
    "\"TYPE\"",
    "\"AS\"",
    "\"END\"",
    "\"DET\"",
    "\"SEMIDET\"",
    "\"MULTI\"",
    "\"NONDET\"",
    "\"BOUND\"",
    "\"DEFAULT\"",
    "\"FACT\"",
    "\"OF\"",
    "\"PERSISTENT\"",
    "\"||\"",
    "\"&&\"",
    "\"::\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"<\"",
    "\">\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"#\"",
    "\"@\"",
    "\"|\"",
    "\"/\"",
    "\":-\"",
    "\"+\"",
    "\"*\"",
    "\"=\"",
    "<SPECIAL>",
    "<SPECIAL_CHAR>",
    "<IDENTIFIER>",
    "<VARIABLE>",
    "<TEMPLATE_VAR>",
    "<JAVA_CLASS>",
    "<REGEXP>",
    "<LOWCASE>",
    "<UPCASE>",
    "<LETTER>",
    "<DIGIT>",
    "\"{\"",
    "<token of kind 70>",
    "\"{\"",
    "\"}\"",
    "\"}\"",
    "\":\"",
  };

}
